"""Editorial + SEO metadata for every blog post and topic hub.

build.py merges this with the article fragments in tools/blog/posts/*.html.
To add a post: drop <slug>.html into tools/blog/posts/, add an entry to POSTS
(and list it under one or more TOPICS), then run `python tools/blog/build.py`.
"""

SITE = 'https://dharmikgohil.art'
TODAY = '2026-10-08'

TOPICS = {
    'unity-game-development': {
        'name': 'Unity Game Development',
        'short': 'Unity',
        'icon': 'bi-controller',
        'title': 'Unity Game Development Articles & Tutorials | Dharmik Gohil',
        'description': 'Unity tutorials, C# tips, mobile optimization and career advice from a working Unity developer: start here if you are learning to build and ship games.',
        'intro': 'Practical Unity writing from shipped projects: how to set up your first scene, write clean C#, keep mobile builds fast and structure a project so it survives its second month.',
        'lead': 'Unity is the engine behind most of the games I have shipped, from Mavericks Battlegrounds to smaller mobile titles. These articles collect what I wish I had known earlier: fundamentals, performance work, project structure and how to turn the skill into a career.',
        'service': ('Unity game development services', '../../services.html'),
        'posts': ['getting-started-unity-game-development', 'unity-game-development-tips', 'mobile-game-optimization', 'game-developer-career-guide'],
    },
    'xr-vr-ar-development': {
        'name': 'AR, VR & XR Development',
        'short': 'XR',
        'icon': 'bi-badge-vr',
        'title': 'Unity XR, VR & AR Development Articles | Dharmik Gohil',
        'description': 'Guides to building VR and AR apps with Unity XR and AR Foundation, plus perspectives on where immersive gaming is heading, from a Unity XR developer.',
        'intro': 'Immersive-tech notes from hands-on work with Unity XR: environment setup, VR basics, AR Foundation, comfort and performance, and what the next few years of spatial gaming look like.',
        'lead': 'XR punishes sloppy performance and rewards careful design. These posts cover how I approach VR and AR projects in Unity, and the industry trends worth paying attention to.',
        'service': ('AR/VR/XR development services', '../../services.html'),
        'posts': ['getting-started-unity-xr', 'vr-ar-future-gaming', 'iit-bombay-techfest-2024-experience'],
    },
    'multiplayer-game-development': {
        'name': 'Multiplayer Game Development',
        'short': 'Multiplayer',
        'icon': 'bi-people-fill',
        'title': 'Multiplayer Game Development: Photon PUN & WebSockets',
        'description': 'How real-time multiplayer games are built: Photon PUN2 in Unity, lobbies, synchronization and latency, with case studies from Mavericks Battlegrounds and LowXena.',
        'intro': 'Networking is where games get hard. These articles walk through Photon PUN2 in Unity and WebSocket-based web multiplayer, using real projects as case studies.',
        'lead': 'I have built a Photon-powered 3D shooter and a WebSocket card game. Both taught me that multiplayer is mostly about state, latency and trust. Here is how those projects were put together.',
        'service': ('Multiplayer game development services', '../../services.html'),
        'posts': ['multiplayer-games-photon-unity', 'mavericks-battlegrounds-game-development-journey', 'lowxena-game-development-insights', 'charusat-expo-3-mavericks-battlegrounds-showcase'],
    },
    'web-development': {
        'name': 'Web & Full-Stack Development',
        'short': 'Web',
        'icon': 'bi-code-slash',
        'title': 'Web & Full-Stack Development Articles | React, Next.js, Git',
        'description': 'Framework decisions and developer fundamentals: React versus Next.js, the Git commands you actually use, and a real-time web game case study.',
        'intro': 'Full-stack lessons from building portfolio sites, client platforms and a real-time web game: choosing frameworks, using Git properly and shipping web projects.',
        'lead': 'Alongside games I build with React, Node.js and MongoDB. These posts cover the decisions that matter most: which framework, how to manage code, and how a production web game fits together.',
        'service': ('Full-stack web development services', '../../services.html'),
        'posts': ['react-vs-nextjs-which-to-choose', 'git-github-essential-commands', 'lowxena-game-development-insights'],
    },
    'hackathons-and-events': {
        'name': 'Hackathons & Tech Events',
        'short': 'Events',
        'icon': 'bi-trophy-fill',
        'title': 'Hackathon & Tech Event Stories | IIT Bombay, Hackron, DAIICT',
        'description': 'First-hand write-ups from hackathons and tech festivals: IIT Bombay Techfest, Hackron 2025 (Blinkit), DAIICT and CHARUSAT Expo 3.0, with what each taught us.',
        'intro': 'What happens when you build something real in 24 hours, or show a game to thousands of visitors. Honest event write-ups with the lessons that stuck.',
        'lead': 'Hackathons and expos compress months of learning into days. These are my accounts of four of them, including the projects we built and what we would do differently.',
        'service': ('Hire me for your project', '../../contact.html'),
        'posts': ['hackron-hackathon-2025-blinkit-experience', 'daiict-hackathon-ai-meeting-monitor', 'iit-bombay-techfest-2024-experience', 'charusat-expo-3-mavericks-battlegrounds-showcase'],
    },
    'career-and-learning': {
        'name': 'Career & Learning',
        'short': 'Career',
        'icon': 'bi-mortarboard-fill',
        'title': 'Game Developer Career & Learning Guides | Dharmik Gohil',
        'description': 'Career roadmap for aspiring game developers plus an honest look at studying computer engineering at CHARUSAT DEPSTAR and how it shaped a game-dev path.',
        'intro': 'How to get started in game development, what to learn, how to build a portfolio, and what a computer-engineering degree did and did not teach me.',
        'lead': 'If you are deciding what to study or how to break into the games industry, start here. These are personal, practical and written from the student side of the journey.',
        'service': ('Work with me', '../../contact.html'),
        'posts': ['game-developer-career-guide', 'charusat-university-experience', 'getting-started-unity-game-development'],
    },
}

POSTS = {
    'getting-started-unity-game-development': {
        'seo_title': 'Getting Started with Unity: Beginner Guide | Dharmik Gohil',
        'description': 'Learn Unity step by step: install the editor, understand GameObjects and components, write your first C# script, add physics and build a simple 2D game.',
        'date': '2026-02-20', 'topic': 'unity-game-development', 'also': [],
        'tags': ['Unity', 'C#', 'Beginner Guide', 'Game Development'],
        'takeaways': ['Unity is component-based: everything is a GameObject plus the components you attach.', 'Learn the editor layout (Scene, Game, Hierarchy, Inspector) before writing code.', 'Physics, a first C# script and a tiny 2D game teach more than any amount of theory.', 'Export early and often so build problems surface while they are cheap to fix.'],
        'faqs': [('Is Unity good for beginners?', 'Yes. Unity has a visual editor, a huge tutorial ecosystem and uses C#, a readable language. You can have a small playable prototype within a weekend.'),
                 ('Do I need to know C# before learning Unity?', 'No. Basic programming concepts are enough to start. You pick up C# as you script movement, input and collisions, which is how this guide is structured.'),
                 ('Should I start with 2D or 3D in Unity?', 'Start with 2D. It removes camera, lighting and model complexity, so you can focus on scripting, physics and game feel before moving to 3D.')],
        'related': ['unity-game-development-tips', 'mobile-game-optimization', 'game-developer-career-guide', 'multiplayer-games-photon-unity'],
        'links': [('multiplayer', 'multiplayer-games-photon-unity'), ('mobile', 'mobile-game-optimization'), ('CHARUSAT University', 'charusat-university-experience'), ('Unity XR', 'getting-started-unity-xr'), ('Mavericks Battlegrounds', 'mavericks-battlegrounds-game-development-journey')],
    },
    'unity-game-development-tips': {
        'seo_title': '5 Essential Unity Game Development Tips | Dharmik Gohil',
        'description': 'Five Unity habits that save projects: master the fundamentals, optimize early, organize assets, write clean C# and test on real devices.',
        'date': '2025-08-21', 'topic': 'unity-game-development', 'also': [],
        'tags': ['Unity Tips', 'C#', 'Performance', 'Project Structure'],
        'takeaways': ['Master GameObjects, transforms, physics and input before reaching for plugins.', 'Pool objects that spawn often and profile before you optimize.', 'Folder structure, naming conventions and version control from day one prevent mess later.', 'Test on the real target device regularly, not just in the editor.'],
        'faqs': [('What is the most common Unity mistake beginners make?', 'Skipping the Profiler. Developers guess at performance problems instead of measuring them, and often optimize the wrong thing.'),
                 ('How should I organize a Unity project?', 'Group assets by type or feature in clear folders, use consistent naming, keep scenes small, and commit to version control from the first day.'),
                 ('Why use object pooling in Unity?', 'Instantiating and destroying objects repeatedly causes garbage-collection spikes. Pooling reuses objects, which keeps frame times stable, especially on mobile.')],
        'related': ['getting-started-unity-game-development', 'mobile-game-optimization', 'git-github-essential-commands', 'game-developer-career-guide'],
        'links': [('mobile', 'mobile-game-optimization'), ('CHARUSAT University', 'charusat-university-experience'), ('XR', 'getting-started-unity-xr'), ('career', 'game-developer-career-guide')],
    },
    'mobile-game-optimization': {
        'seo_title': 'Unity Mobile Game Optimization Techniques | Dharmik Gohil',
        'description': 'Make Unity games run smoothly on phones: understand hardware limits, reduce draw calls, compress textures, manage memory and profile on real devices.',
        'date': '2025-08-18', 'topic': 'unity-game-development', 'also': [],
        'tags': ['Mobile Games', 'Optimization', 'Unity Profiler', 'Performance'],
        'takeaways': ['Mobile GPUs and thermal limits are the real constraint, so design for them from the start.', 'Texture atlases and compression cut draw calls and memory.', 'Profile on real devices; editor performance is not representative.', 'Fix the biggest bottleneck first rather than micro-optimizing everything.'],
        'faqs': [('How do I improve Unity performance on mobile?', 'Reduce draw calls with batching and atlases, compress textures, limit real-time lights and overdraw, pool objects, and profile on actual devices.'),
                 ('What frame rate should a mobile game target?', 'Most mobile games target 30 or 60 FPS. Pick one early and design your budget around it, since consistency matters more than a high peak.'),
                 ('Why does my game run fine in the editor but lag on phones?', 'Phones have far weaker GPUs, less memory and thermal throttling. Editor results ignore those limits, so always test builds on target hardware.')],
        'related': ['unity-game-development-tips', 'getting-started-unity-game-development', 'getting-started-unity-xr', 'game-developer-career-guide'],
        'links': [('Unity', 'getting-started-unity-game-development'), ('VR', 'vr-ar-future-gaming'), ('optimization', 'unity-game-development-tips')],
    },
    'game-developer-career-guide': {
        'seo_title': 'Game Developer Career Guide: Skills, Portfolio, Jobs',
        'description': 'How to start a game development career: roles, essential skills, learning path, portfolio advice, finding a first job and growing from there.',
        'date': '2025-08-10', 'topic': 'unity-game-development', 'also': ['career-and-learning'],
        'tags': ['Career Guide', 'Game Developer', 'Portfolio', 'Learning Path'],
        'takeaways': ['Games studios hire for specific roles (gameplay, tools, graphics, design) so pick a lane.', 'A small number of finished, playable projects beats many abandoned prototypes.', 'Your portfolio should show playable builds and what you personally built.', 'Game jams, hackathons and community work are legitimate experience.'],
        'faqs': [('How do I become a game developer?', 'Learn an engine such as Unity and its language, build and finish small games, publish them, and present them in a portfolio that shows what you personally built.'),
                 ('Do I need a degree to work in game development?', 'Not strictly. Studios mostly evaluate shipped work and skills, though a computer science degree helps with fundamentals and some employers.'),
                 ('Which programming language should I learn for games?', 'C# if you use Unity, C++ for Unreal Engine and low-level engine work. Pick the one that matches the engine you want to ship with.')],
        'related': ['getting-started-unity-game-development', 'charusat-university-experience', 'unity-game-development-tips', 'hackron-hackathon-2025-blinkit-experience'],
        'links': [('Unity', 'getting-started-unity-game-development'), ('Git', 'git-github-essential-commands'), ('mobile', 'mobile-game-optimization'), ('VR', 'vr-ar-future-gaming')],
    },
    'getting-started-unity-xr': {
        'cover': '../assets/dharmik-gohil-vr-ar-technology-showcase-1.png',
        'seo_title': 'Getting Started with Unity XR: VR & AR Guide',
        'description': 'Build your first VR and AR apps in Unity: set up the XR environment, learn VR basics, use AR Foundation and apply performance and comfort best practices.',
        'date': '2025-08-05', 'topic': 'xr-vr-ar-development', 'also': [],
        'tags': ['Unity XR', 'VR', 'AR Foundation', 'XR Toolkit'],
        'takeaways': ['XR Interaction Toolkit and AR Foundation cover most VR and AR projects in Unity.', 'Hold a steady frame rate: dropped frames cause discomfort in VR.', 'Design interactions for the headset or phone, not as ported desktop controls.', 'Test on real devices early; emulators hide comfort and tracking problems.'],
        'faqs': [('What is Unity XR?', 'Unity XR is the set of tools, packages and plugins in Unity for building virtual, augmented and mixed reality apps across headsets and mobile devices.'),
                 ('What is the difference between AR Foundation and the XR Interaction Toolkit?', 'AR Foundation handles augmented reality on phones and tablets (tracking, planes, anchors). The XR Interaction Toolkit provides interaction building blocks for VR and AR controllers and hands.'),
                 ('Why is performance so important in VR?', 'VR renders two views at high refresh rates close to your eyes. Low or unstable frame rates cause visible judder and motion sickness, so budgets are far stricter than for flat games.')],
        'related': ['vr-ar-future-gaming', 'unity-game-development-tips', 'mobile-game-optimization', 'iit-bombay-techfest-2024-experience'],
        'links': [('Unity', 'getting-started-unity-game-development'), ('mobile', 'mobile-game-optimization'), ('VR', 'vr-ar-future-gaming')],
    },
    'vr-ar-future-gaming': {
        'seo_title': 'The Future of VR and AR Gaming | Dharmik Gohil',
        'description': 'Where VR and AR gaming stands today, why it is growing, the development challenges and opportunities, and how to start building with Unity XR.',
        'date': '2025-08-20', 'topic': 'xr-vr-ar-development', 'also': [],
        'tags': ['VR', 'AR', 'Future of Gaming', 'Immersive Tech'],
        'takeaways': ['Immersion and presence are what separate VR and AR from flat-screen gaming.', 'Hardware cost, comfort and content depth are still the main hurdles.', 'Unity XR lets one skill set target headsets and phones.', 'Starting small with a focused prototype is the best entry point.'],
        'faqs': [('Is VR gaming the future?', 'VR and AR are growing segments with strong potential for immersive experiences, though adoption depends on hardware cost, comfort and compelling content.'),
                 ('How do I start developing VR or AR games?', 'Learn Unity, install the XR packages, pick a target device, and prototype one simple interaction. Our Unity XR guide walks through setup in detail.'),
                 ('What are the biggest challenges in XR game development?', 'Performance budgets, motion comfort, input design for new controllers and hands, and limited audience size compared with mobile or PC.')],
        'related': ['getting-started-unity-xr', 'iit-bombay-techfest-2024-experience', 'unity-game-development-tips', 'game-developer-career-guide'],
        'links': [('Unity XR', 'getting-started-unity-xr'), ('multiplayer', 'multiplayer-games-photon-unity'), ('mobile', 'mobile-game-optimization')],
    },
    'multiplayer-games-photon-unity': {
        'seo_title': 'Multiplayer Games with Photon PUN2 & Unity: Guide',
        'description': 'Build multiplayer Unity games with Photon PUN2: rooms and lobbies, player synchronization, RPCs, spawning, latency handling and lessons from a shipped shooter.',
        'date': '2026-02-15', 'topic': 'multiplayer-game-development', 'also': ['unity-game-development'],
        'tags': ['Photon PUN2', 'Multiplayer', 'Networking', 'Unity'],
        'takeaways': ['Photon PUN2 handles matchmaking and relay so you can focus on gameplay.', 'Synchronize only what you must; every extra synced value costs bandwidth.', 'RPCs and PhotonView ownership are the core mental model.', 'Plan for latency with interpolation instead of pretending it does not exist.'],
        'faqs': [('What is Photon PUN2?', 'Photon Unity Networking 2 is a networking framework for Unity that provides matchmaking, rooms, state synchronization and RPCs over Photon cloud servers.'),
                 ('How do I synchronize players in Photon?', 'Attach a PhotonView and PhotonTransformView to the player prefab, instantiate it with PhotonNetwork.Instantiate, and let the owner drive movement while others interpolate.'),
                 ('How do you handle lag in a multiplayer game?', 'Interpolate remote players, send updates at a sensible rate, avoid syncing unnecessary data, and design gameplay so small timing differences are not fatal.')],
        'related': ['mavericks-battlegrounds-game-development-journey', 'getting-started-unity-game-development', 'lowxena-game-development-insights', 'mobile-game-optimization'],
        'links': [('Mavericks Battlegrounds', 'mavericks-battlegrounds-game-development-journey'), ('CHARUSAT Expo 3.0', 'charusat-expo-3-mavericks-battlegrounds-showcase'), ('mobile', 'mobile-game-optimization'), ('Unity', 'getting-started-unity-game-development')],
    },
    'mavericks-battlegrounds-game-development-journey': {
        'seo_title': 'Mavericks Battlegrounds: Unity 6 Multiplayer Case Study',
        'description': 'The development story of Mavericks Battlegrounds, a Unity 6 and Photon PUN multiplayer arena shooter: team, process, timeline, tech stack and screenshots.',
        'date': '2025-06-12', 'topic': 'multiplayer-game-development', 'also': ['unity-game-development'],
        'tags': ['Mavericks Battlegrounds', 'Unity 6', 'Photon PUN', 'Case Study'],
        'takeaways': ['Built with Unity 6 and Photon PUN by a student team from CHARUSAT DEPSTAR.', 'Development ran from November 2024 to the first release on June 12, 2025.', 'An agile process with short iterations kept a small team shipping.', 'Public showcases and playtests drove the most useful feedback.'],
        'faqs': [('What is Mavericks Battlegrounds?', 'Mavericks Battlegrounds is a multiplayer battle arena shooter built in Unity 6 with Photon PUN networking by a student team at CHARUSAT University.'),
                 ('When was Mavericks Battlegrounds released?', 'Development started in November 2024 and the first version, The War Zone (1.0), was released on June 12, 2025.'),
                 ('Where can I play Mavericks Battlegrounds?', 'The game is published on itch.io. You can find the link on the portfolio games page and in the navigation under My Games.')],
        'related': ['multiplayer-games-photon-unity', 'charusat-expo-3-mavericks-battlegrounds-showcase', 'lowxena-game-development-insights', 'getting-started-unity-game-development'],
        'links': [('Photon', 'multiplayer-games-photon-unity'), ('Git', 'git-github-essential-commands'), ('CHARUSAT', 'charusat-university-experience'), ('Unity XR', 'getting-started-unity-xr')],
    },
    'charusat-expo-3-mavericks-battlegrounds-showcase': {
        'seo_title': 'CHARUSAT Expo 3.0: Showcasing Mavericks Battlegrounds',
        'description': 'How Mavericks Battlegrounds became the only IT Department project selected for CHARUSAT Expo 3.0, what 5000+ visitors told us and the changes we shipped after.',
        'date': '2025-12-16', 'topic': 'hackathons-and-events', 'also': ['multiplayer-game-development'],
        'tags': ['CHARUSAT Expo', 'Mavericks Battlegrounds', 'Playtesting', 'Exhibition'],
        'takeaways': ['Mavericks Battlegrounds was the only IT Department project selected for the expo.', 'Watching thousands of people play exposed usability issues we had stopped noticing.', 'We turned structured visitor feedback into a concrete list of changes.', 'Live demos teach more about game feel than any internal test.'],
        'faqs': [('What is CHARUSAT Expo 3.0?', 'CHARUSAT Expo 3.0 is a university showcase at CHARUSAT where student teams present their projects to students, faculty and visitors.'),
                 ('Which project was selected from the IT Department?', 'Mavericks Battlegrounds, a Unity 6 multiplayer arena shooter, was the only IT Department project selected for the expo.'),
                 ('What did you learn from showing a game to thousands of people?', 'Onboarding and controls matter more than we thought. Live observation revealed confusion points that testers who knew the game never hit.')],
        'related': ['mavericks-battlegrounds-game-development-journey', 'multiplayer-games-photon-unity', 'charusat-university-experience', 'hackron-hackathon-2025-blinkit-experience'],
        'links': [('multiplayer', 'multiplayer-games-photon-unity'), ('CHARUSAT University', 'charusat-university-experience'), ('Mavericks Battlegrounds', 'mavericks-battlegrounds-game-development-journey')],
    },
    'lowxena-game-development-insights': {
        'seo_title': 'LowXena: Building a Multiplayer Card Game with React',
        'description': 'Inside LowXena, a real-time multiplayer least-count card game: scoring logic, 3D felt table, React 19 front end and WebSocket state synchronization.',
        'date': '2026-05-21', 'topic': 'multiplayer-game-development', 'also': ['web-development'],
        'tags': ['LowXena', 'React 19', 'WebSockets', 'Card Game'],
        'takeaways': ['LowXena inverts normal card games: the lowest total wins and 200 points knocks you out.', 'The server is the source of truth; clients render state received over WebSockets.', 'Custom hand-evaluation logic drives scoring and the Showdown rule.', 'A 3D felt table and polished UI make a browser game feel premium.'],
        'faqs': [('What is LowXena?', 'LowXena is a multiplayer card game based on least-count rules, where players try to hold the lowest total and the last player standing wins.'),
                 ('What technology is LowXena built with?', 'A React 19 front end with real-time WebSocket communication and custom game logic for hand scoring and Showdown resolution.'),
                 ('How does state sync work in a web multiplayer card game?', 'The server owns the game state and broadcasts updates over WebSockets. Clients send intents, the server validates them and every player receives the result.')],
        'related': ['multiplayer-games-photon-unity', 'react-vs-nextjs-which-to-choose', 'mavericks-battlegrounds-game-development-journey', 'git-github-essential-commands'],
        'links': [('multiplayer', 'multiplayer-games-photon-unity'), ('React', 'react-vs-nextjs-which-to-choose')],
    },
    'react-vs-nextjs-which-to-choose': {
        'seo_title': 'React vs Next.js in 2026: Which Should You Choose?',
        'description': 'React or Next.js? Compare rendering strategies, routing, SEO and when each makes sense, with a clear recommendation from a full-stack developer.',
        'date': '2026-02-18', 'topic': 'web-development', 'also': [],
        'tags': ['React', 'Next.js', 'SEO', 'Full-Stack'],
        'takeaways': ['React is a UI library; Next.js is a framework built on it with routing and rendering built in.', 'For public, SEO-sensitive sites, server rendering or static generation in Next.js is a big advantage.', 'For apps behind a login, plain React with Vite is often simpler.', 'Ship something, then iterate; framework debates should not stall projects.'],
        'faqs': [('Should I use React or Next.js?', 'Use Next.js for content or marketing sites that need SEO, server rendering and file-based routing. Use plain React with Vite for dashboards and apps behind a login.'),
                 ('Is Next.js better for SEO than React?', 'Generally yes. Next.js can render HTML on the server or at build time, so crawlers see content immediately, whereas client-only React depends on JavaScript execution.'),
                 ('Can I learn Next.js without learning React first?', 'No. Next.js is built on React, so you need React fundamentals (components, props, state, hooks) before the framework makes sense.')],
        'related': ['git-github-essential-commands', 'lowxena-game-development-insights', 'game-developer-career-guide', 'unity-game-development-tips'],
        'links': [('CHARUSAT University', 'charusat-university-experience'), ('full-stack', 'lowxena-game-development-insights')],
    },
    'git-github-essential-commands': {
        'seo_title': 'Git & GitHub Commands Cheatsheet for Developers',
        'description': 'The Git and GitHub commands developers use daily: setup, staging, branching, merging and rebasing, remotes, stashing, history and undoing mistakes.',
        'date': '2026-02-12', 'topic': 'web-development', 'also': ['unity-game-development'],
        'tags': ['Git', 'GitHub', 'Cheatsheet', 'Version Control'],
        'takeaways': ['Commit small and often with messages that explain why.', 'Branch for every feature; merge or rebase deliberately.', 'Stashing lets you switch context without losing work in progress.', 'A proper .gitignore keeps build output and secrets out of the repository.'],
        'faqs': [('What Git commands should every developer know?', 'git init, clone, status, add, commit, branch, checkout or switch, merge, pull, push, stash and log cover the vast majority of daily work.'),
                 ('What is the difference between git merge and git rebase?', 'Merge joins histories with a merge commit and preserves branch history. Rebase replays your commits on top of another branch for a linear history.'),
                 ('How do I undo my last commit?', 'Use git reset --soft HEAD~1 to undo the commit but keep changes staged, or git revert to create a new commit that reverses it safely on shared branches.')],
        'related': ['react-vs-nextjs-which-to-choose', 'unity-game-development-tips', 'getting-started-unity-game-development', 'lowxena-game-development-insights'],
        'links': [('Unity', 'unity-game-development-tips'), ('Mavericks Battlegrounds', 'mavericks-battlegrounds-game-development-journey')],
    },
    'hackron-hackathon-2025-blinkit-experience': {
        'seo_title': 'Hackron Hackathon 2025: Building SafaiNova for Blinkit',
        'description': 'Our 24-hour build at Hackron 2025 (Blinkit and Newton School of Technology): SafaiNova, an AI and IoT waste-management concept for dark stores, and what we learned.',
        'date': '2025-04-01', 'topic': 'hackathons-and-events', 'also': [],
        'tags': ['Hackron 2025', 'Blinkit', 'SafaiNova', 'Hackathon'],
        'takeaways': ['The challenge: automating waste segregation in quick-commerce dark stores.', 'SafaiNova combined IoT sensing, machine learning classification and automated sorting.', 'In a 24-hour build, scope control matters more than features.', 'Presenting clearly counted as much as the code.'],
        'faqs': [('What is Hackron Hackathon 2025?', 'Hackron 2025 was a 24-hour hackathon at DY Patil University, Pune, sponsored by Blinkit and Newton School of Technology.'),
                 ('What did your team build?', 'SafaiNova, a concept for automating waste segregation and management in Blinkit dark stores using IoT sensors, machine learning and automated sorting.'),
                 ('How do you survive a 24-hour hackathon?', 'Pick a narrow scope, split work by strength, build a working end-to-end demo first, and reserve time to rehearse the pitch.')],
        'related': ['daiict-hackathon-ai-meeting-monitor', 'iit-bombay-techfest-2024-experience', 'charusat-expo-3-mavericks-battlegrounds-showcase', 'game-developer-career-guide'],
        'links': [('CHARUSAT', 'charusat-university-experience')],
    },
    'daiict-hackathon-ai-meeting-monitor': {
        'seo_title': 'DAIICT Hackathon: Building an AI Meeting Monitor',
        'description': 'How our team built an AI meeting assistant at the DAIICT Hackathon in Gandhinagar: real-time transcription, summaries, action items and engagement insights.',
        'date': '2026-01-23', 'topic': 'hackathons-and-events', 'also': [],
        'tags': ['DAIICT', 'AI', 'Hackathon', 'Meeting Assistant'],
        'takeaways': ['The problem: meeting content gets lost, action items go untracked and notes cost attention.', 'The solution captured transcripts, summaries, action items and engagement signals.', 'Defining a tight use case made the demo convincing.', 'AI features need a clear user outcome, not just a model.'],
        'faqs': [('What did you build at the DAIICT Hackathon?', 'An AI Meeting Monitor application that transcribes meetings in real time, summarizes them, extracts action items and surfaces engagement insights.'),
                 ('Where was the DAIICT Hackathon held?', 'At DAIICT (Dhirubhai Ambani Institute of Information and Communication Technology) in Gandhinagar, Gujarat.'),
                 ('Why build an AI meeting assistant?', 'Meetings cost hours, yet decisions and follow-ups get lost. Automating capture and summary lets participants focus on the conversation.')],
        'related': ['hackron-hackathon-2025-blinkit-experience', 'iit-bombay-techfest-2024-experience', 'react-vs-nextjs-which-to-choose', 'game-developer-career-guide'],
        'links': [('CHARUSAT', 'charusat-university-experience'), ('React', 'react-vs-nextjs-which-to-choose')],
    },
    'iit-bombay-techfest-2024-experience': {
        'seo_title': 'IIT Bombay TechFest 2024: Workshops, Robots & Takeaways',
        'description': 'My experience at IIT Bombay TechFest 2024, Asia’s largest science and tech festival: a game development workshop, robotics, drones and what I took home.',
        'date': '2024-12-17', 'topic': 'hackathons-and-events', 'also': ['xr-vr-ar-development'],
        'tags': ['IIT Bombay', 'TechFest 2024', 'Robotics', 'Game Development Workshop'],
        'takeaways': ['TechFest 2024 ran December 13 to 17 at IIT Bombay in Mumbai.', 'The game development workshop covered the path from concept to execution.', 'Robotics, drones and automotive exhibits showed how hardware and software converge.', 'Events like this are the fastest way to widen what you think is possible.'],
        'faqs': [('When was IIT Bombay TechFest 2024?', 'TechFest 2024 took place from December 13 to 17, 2024, at IIT Bombay in Mumbai.'),
                 ('What is IIT Bombay TechFest?', 'TechFest is IIT Bombay’s annual science and technology festival, described as Asia’s largest, with workshops, competitions, exhibitions and talks.'),
                 ('Was there game development content at TechFest?', 'Yes. I attended a hands-on game development workshop that walked through the process from concept to implementation.')],
        'related': ['vr-ar-future-gaming', 'getting-started-unity-xr', 'hackron-hackathon-2025-blinkit-experience', 'charusat-university-experience'],
        'links': [('Unity', 'getting-started-unity-game-development'), ('VR', 'vr-ar-future-gaming'), ('CHARUSAT', 'charusat-university-experience')],
    },
    'charusat-university-experience': {
        'seo_title': 'My CHARUSAT DEPSTAR Journey: Engineering to Game Dev',
        'description': 'What studying computer engineering at CHARUSAT University’s DEPSTAR College was like, how it led me into game development and advice for future students.',
        'date': '2025-08-15', 'topic': 'career-and-learning', 'also': [],
        'tags': ['CHARUSAT', 'DEPSTAR', 'Computer Engineering', 'Student Life'],
        'takeaways': ['A strong CS foundation made game programming far easier to learn.', 'Projects and clubs taught more than lectures alone.', 'The path into game development started with curiosity and small builds.', 'Advice: build things while you study.'],
        'faqs': [('What is DEPSTAR at CHARUSAT?', 'DEPSTAR (Devang Patel Institute of Advance Technology and Research) is a college at CHARUSAT University in Gujarat offering engineering programs.'),
                 ('Can you become a game developer with a computer engineering degree?', 'Yes. Computer engineering gives you programming, data structures and systems knowledge that transfers directly to game development, alongside personal projects.'),
                 ('What advice do you have for CHARUSAT students?', 'Start building early, join teams and events, publish your work and learn Git, because projects and shipped work matter as much as grades.')],
        'related': ['game-developer-career-guide', 'charusat-expo-3-mavericks-battlegrounds-showcase', 'hackron-hackathon-2025-blinkit-experience', 'getting-started-unity-game-development'],
        'links': [('Unity', 'getting-started-unity-game-development'), ('career', 'game-developer-career-guide'), ('hackathon', 'hackron-hackathon-2025-blinkit-experience')],
    },
}
